# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf58de5c62615ba7255d2471931d380303f7dae0ed17805f70c5c3824984219dd1b1d1d4ae353eb61d89fcf7b41355c16fe8e633d86f61936ab97bbadca684fa

test:
  secret_key_base: 0c4307cff4f6b4706447793acc8c1867b670a6ac85d2b2b86867d7e6a4697f41bf550c1fc0c9361822ec8a2e4f254f5db455beb6666dc5790b7781f1094a5b06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
